### ISSUE TITLE
X11/X.h not found

### ISSUE THREAD

**Issue by clad26** [JuliaBinaryWrappers/Xorg_libXpm_jll.jl#1]
No idea whats causing it!
```
In file included from /workspace/artifacts/b7b1837330201e080ac0d66832978abf20e38bfb/include/X11/xpm.h:76:0,
                 from gdxpm.c:37:
/workspace/artifacts/431a0e3706ffe717ab5d35c47bc38626c6169504/include/X11/Xlib.h:44:19: fatal error: X11/X.h: No such file or directory
 #include <X11/X.h>
                   ^
compilation terminated.

                   ^
```

**Comment by giordano** [comment]
You need to add [`Xorg_xorgproto_jll`](https://github.com/JuliaBinaryWrappers/Xorg_xorgproto_jll.jl) as [`BuildDependency`](https://docs.binarybuilder.org/stable/reference/#BinaryBuilderBase.BuildDependency) in your recipe

**Comment by clad26** [comment]
Xorg_libXpm_jll
and Xorg_xorgproto_jll.jl
Both?

**Comment by giordano** [comment]
`Xorg_libXpm_jll` contains binary library, `Xorg_xorgproto_jll` only the header files
